global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'userloginservice'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['userloginservice:80']

  - job_name: 'envoy'
    metrics_path: '/stats/prometheus'
    static_configs:
      - targets: ['envoy:9901']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgresql:5432']
    
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
